#!/usr/bin/env npx tsx
/**
 * Pre-build script: reads the version from package.json and writes it as a
 * typed constant to src/generated/version.ts so that the MCP server reports
 * the correct version at runtime without runtime JSON parsing.
 *
 * Run automatically via the `prebuild` npm hook before `tsc`.
 *
 * Lifted from tugudush/video-context-mcp/scripts/sync-version.ts (same
 * author, June 2026).
 */

import { readFileSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

const pkg = JSON.parse(
  readFileSync(join(__dirname, '../package.json'), 'utf-8')
) as {
  version: string
}

const outDir = join(__dirname, '../src/generated')
const outFile = join(outDir, 'version.ts')

mkdirSync(outDir, { recursive: true })
writeFileSync(
  outFile,
  `// Auto-generated by scripts/sync-version.ts — do not edit\nexport const VERSION = '${pkg.version}'\n`,
  'utf-8'
)

console.log(`[sync-version] wrote ${outFile} (VERSION=${pkg.version})`)
